# version: '3.6'
# services:
#   db:
#     image: postgres:10.1-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#         - POSTGRES_DB=docker_ass
#         - POSTGRES_USER=employee3
#         - POSTGRES_PASSWORD=employee3
#     ports:
#       - "5432"
#   web:
#     build: .
#     command: bash -c "/code/prestart.sh"
#     command: python /code/manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/code
#     ports:
#       - 8000:8000
#     depends_on:
#       - db

# volumes:
#   postgres_data: {}

version: '3.6'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
       - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: